### ISSUE TITLE
Push to Master?

### ISSUE THREAD

**Issue by vanDeventer** [D7039E-E7032E/Project-Report#7] opened 2019-09-13 07:35 UTC
Hi,

You seem to only have one branch and no forks. When you push to the master branch, how is the reviewer checking the pull request?

Best regards,

Jan

**Comment by carfri** [comment] 2019-09-13 08:23
Hi Jan,

The master branch is currently protected from any remote pushes. So the only way to update the master branch is via a merge with a different branch. The process would be as follow. First you need to checkout a new branch that is dedicated to a specific issue. We are currently working on defining issues, notes can be found under the project tab of each repo. When the issue is completed and you want to merge your branch with master you need approval from 2 different group members. This way we can avoid any annoying merge issues and it is less likely that there will be introduced bugs to the master when you have 2 people reviewing your code.

When the branch have been merged and the issue has been closed we delete that branch. We do this to avoid cluttering our repos with branches that are not actively developed or updated. All pull requests can still be found [here](https://github.com/D7039E-E7032E/Project-Report/pulls?q=is%3Apr+is%3Aclosed) . This will be usefull if bad code is introduced at any point during the project we can go here to troubleshoot and identify what code block require reconsideration.

Hope that answers your question!

Best regards,

Carl

**Comment by zachtyll** [comment] 2019-09-15 16:58
I have added Carls explanation of our workflow to the wiki and will now close this issue. If something is still unclear feel free to let us know!

**Closed as completed by zachtyll** 2019-09-15 16:58 UTC
